### ISSUE TITLE
DiceBear works without this fork in the browser

### ISSUE THREAD

**Issue by FlorianKoerner** [hustLer2k/dicebear-browser#1]
DiceBear works without this fork in the browser. If you have problems with the original package, let's find a solution together.

**Comment by hustLer2k** [comment]
Add me on discord +_player#5016 so we can discuss further.

**Comment by FlorianKoerner** [comment]
Sorry, but I only provide support in the official repository so that the community can benefit from discussed problems and solutions.

Feel free to use the GitHub discussions to describe your problems:
https://github.com/dicebear/dicebear/discussions

And please correct the license. Calling you the author is pretty cheeky.
https://github.com/hustLer2k/dicebear-browser/blob/main/LICENSE.MD

**Comment by FlorianKoerner** [comment]
Thanks for the quick fix on the license.

My guess is that you ran into a problem with DiceBear in the context of your "pimp" project. (Interesting project, by the way.) I'm looking into using DiceBear in the context of Next.js. I could imagine a problem in SSR mode.

**Comment by FlorianKoerner** [comment]
Could not find any problems.
https://github.com/FlorianKoerner/dicebear-nextjs

**Comment by hustLer2k** [comment]
That's right. The project fails to compile with the following errors:
```
./node_modules/@dicebear/converter/lib/node/core.js:36:26
Module not found: Can't resolve '@resvg/resvg-js'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@dicebear/converter/lib/node/index.js
./node_modules/@dicebear/core/lib/core.js
./node_modules/@dicebear/core/lib/index.js
./src/app/account/setup/Previewer.tsx
./src/app/account/setup/page.tsx
```


```
./node_modules/@dicebear/converter/lib/node/core.js:57:0
Module not found: Can't resolve 'exiftool-vendored'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@dicebear/converter/lib/node/index.js
./node_modules/@dicebear/core/lib/core.js
./node_modules/@dicebear/core/lib/index.js
./src/app/account/setup/Previewer.tsx
./src/app/account/setup/page.tsx
```

The component where the error is thrown if dicebear is used - https://github.com/hustLer2k/pimp/blob/main/src/app/account/setup/Previewer.tsx.

If I disable ssr it works though

**Comment by hustLer2k** [comment]
Should I create an issue in the dicebear repo?

**Comment by FlorianKoerner** [comment]
Okay, I'm going to try again directly with your project. There has to be a difference somewhere. :)

**Comment by FlorianKoerner** [comment]
You use the experimental "app" directory in your Next.js application.
https://beta.nextjs.org/docs/app-directory-roadmap

This doesn't seem to work with dependencies that provide a version for the browser and a version for Node.js.
https://github.com/dicebear/dicebear/blob/main/packages/%40dicebear/converter/package.json#L19-L24

NextJS tries to package the frontend build with the server dependencies here as well, unlike the old "pages" directory. This does not work.

Unfortunately, I haven't found a bug in Next about this yet. It would probably have to be created with an MWE in the Next.js project.

Workaround:

```
// next.config.js
const path = require('path');

/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
  },
  webpack: (config, { isServer }) => {
    config.resolve.alias['@dicebear/converter'] = path.resolve(__dirname, 'node_modules/@dicebear/converter/lib/index.js');
    
    return config;
  }
}

module.exports = nextConfig
```

**Comment by hustLer2k** [comment]
Thanks, will test it out.

**Comment by hustLer2k** [comment]
It works, thanks @FlorianKoerner. This package is now deprecated and will be removed soon.

**Comment by Arinji2** [comment]
This workaround doesnt seem to work for me. 
My packages
dependencies": {
    "@dicebear/collection": "^7.0.1",
    "@dicebear/converter": "^7.0.1",
    "@dicebear/core": "^7.0.1",
    "@spotify/web-api-ts-sdk": "^1.1.2",
    "lucide-react": "^0.288.0",
    "next": "^13.5.5",
    "pocketbase": "^0.18.3",
    "react": "^18",
    "react-dom": "^18",
    "react-toastify": "^9.1.3",
    "zod": "^3.22.4"
  },
  
  
  
![image](https://github.com/hustLer2k/dicebear-browser/assets/87296817/e51089c0-3be1-4dba-9657-9cb8a5171afe)

**Comment by dclipca** [comment]
With `next.config.mjs` and `"next": "14.1.4"` (you have to `npm i @dicebear/converter`):

```ts
import path from 'path';
import { fileURLToPath } from 'url'; 

/** @type {import('next').NextConfig} */

// Convert the module URL to a directory path
const __dirname = path.dirname(fileURLToPath(import.meta.url));

const nextConfig = {
  webpack: (config, { isServer }) => {
    config.resolve.alias["@dicebear/converter"] = path.resolve(
      __dirname,
      "node_modules/@dicebear/converter/lib/index.js"
    );

    return config;
  },
};
```

**Comment by SpinBoxx** [comment]
> With `next.config.mjs` and `"next": "14.1.4"` (you have to `npm i @dicebear/converter`):
> 
> ```ts
> import path from 'path';
> import { fileURLToPath } from 'url'; 
> 
> /** @type {import('next').NextConfig} */
> 
> // Convert the module URL to a directory path
> const __dirname = path.dirname(fileURLToPath(import.meta.url));
> 
> const nextConfig = {
>   webpack: (config, { isServer }) => {
>     config.resolve.alias["@dicebear/converter"] = path.resolve(
>       __dirname,
>       "node_modules/@dicebear/converter/lib/index.js"
>     );
> 
>     return config;
>   },
> };
> ```

Thanks it works for me with     `"next": "14.1.4",`
